#import "../../src/lib.typ": *
#maquette(nombre-qr: 2)[
  #exercice(entrainement: "https://a.b/0")[E0]
  #exercice(entrainement: "https://a.b/1")[E1]
  #exercice(entrainement: "https://a.b/2")[E2]
  #exercice(entrainement: "https://a.b/3")[E3]
  #exercice(entrainement: "https://a.b/4")[E4]
  #exercice(entrainement: "https://a.b/5")[E5]
  #exercice(entrainement: "https://a.b/6")[E6]
  #exercice(entrainement: "https://a.b/7")[E7]
  #exercice(entrainement: "https://a.b/8")[E8]
  #exercice(entrainement: "https://a.b/9")[E9]
  #exercice(entrainement: "https://a.b/10")[E10]
  #exercice(entrainement: "https://a.b/11")[E11]
  #exercice(entrainement: "https://a.b/12")[E12]
  #exercice(entrainement: "https://a.b/13")[E13]
  #exercice(entrainement: "https://a.b/14")[E14]
  #exercice(entrainement: "https://a.b/15")[E15]
]
